name: Revshell Generator CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Package
      run: pip install .
    - name: Run Tests
      run: python3 -m unittest test_generator
      env:
        PYTHONPATH: ${{ github.workspace }}/src/tests:${{ github.workspace }}/src/reverseshellgenerator:${{ env.PYTHONPATH }}

  publish-test-pypi:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs: test
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install PyPA/Build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
  publish-pypi:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master'
      needs: test
      steps:
        - uses: actions/checkout@master
        - name: Set up Python 3.9
          uses: actions/setup-python@v1
          with:
            python-version: 3.9
        - name: Install PyPA/Build
          run: >-
            python -m
            pip install
            build
            --user
        - name: Build a binary wheel and a source tarball
          run: >-
            python -m
            build
            --sdist
            --wheel
            --outdir dist/
        - name: Publish distribution to PyPI
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}
